<section class="col-xs-12 main-content">
<h1>О нас</h1>
<div class="page-news">
<div class="page-news_wrap">
<div class="page-news-gal"><div class="lSSlideOuter "><div class="lSSlideWrapper usingCss"><div id="gallery" class="gallery list-unstyled lightSlider lSSlide" style="width: 4059px; transform: translate3d(-451px, 0px, 0px); height: 300px; padding-bottom: 0%;"><a href="assets/cache/images/o_nas/o_nas1-800x-309.jpg" class="gal clone left" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/o_nas1-450x300-b4c.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/4-800x-8cd.jpg" class="gal lslide active" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/4-450x300-68e.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/1-800x-96b.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/1-450x300-ca2.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/3-800x-8cd.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/3-450x300-68e.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/2-800x-b18.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/2-450x300-e0c.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/6-800x-963.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/6-450x300-9be.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/o_nas-800x-309.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/o_nas-450x300-b4c.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/o_nas1-800x-309.jpg" class="gal lslide" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/o_nas1-450x300-b4c.jpg" alt="О нас"></a><a href="assets/cache/images/o_nas/4-800x-8cd.jpg" class="gal clone right" data-fancybox-group="gallery" title="О нас" style="width: 450px; margin-right: 1px;"><img src="assets/cache/images/o_nas/4-450x300-68e.jpg" alt="О нас"></a></div><div class="lSAction"><a class="lSPrev"></a><a class="lSNext"></a></div></div></div></div>
<div class="podel_news"><script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script><div class="yashare-auto-init" data-yasharel10n="ru" data-yasharetype="none" data-yasharequickservices="vkontakte,facebook,twitter"><span class="b-share"><a rel="nofollow" target="_blank" title="ВКонтакте" class="b-share__handle b-share__link b-share-btn__vkontakte" href="https://share.yandex.net/go.xml?service=vkontakte&amp;url=https%3A%2F%2Fmebeldorff.com.ua%2Fo_nas.html&amp;title=%D0%9E%20%D0%BD%D0%B0%D1%81%20-%20%D0%9A%D0%B0%D0%BA%20%D0%BF%D1%80%D0%BE%D0%B9%D1%82%D0%B8%20%D0%B2%20%D0%BC%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%20%D0%9C%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%B4%D0%BE%D1%80%D1%84" data-service="vkontakte"><span class="b-share-icon b-share-icon_vkontakte"></span></a><a rel="nofollow" target="_blank" title="Facebook" class="b-share__handle b-share__link b-share-btn__facebook" href="https://share.yandex.net/go.xml?service=facebook&amp;url=https%3A%2F%2Fmebeldorff.com.ua%2Fo_nas.html&amp;title=%D0%9E%20%D0%BD%D0%B0%D1%81%20-%20%D0%9A%D0%B0%D0%BA%20%D0%BF%D1%80%D0%BE%D0%B9%D1%82%D0%B8%20%D0%B2%20%D0%BC%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%20%D0%9C%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%B4%D0%BE%D1%80%D1%84" data-service="facebook"><span class="b-share-icon b-share-icon_facebook"></span></a><a rel="nofollow" target="_blank" title="Twitter" class="b-share__handle b-share__link b-share-btn__twitter" href="https://share.yandex.net/go.xml?service=twitter&amp;url=https%3A%2F%2Fmebeldorff.com.ua%2Fo_nas.html&amp;title=%D0%9E%20%D0%BD%D0%B0%D1%81%20-%20%D0%9A%D0%B0%D0%BA%20%D0%BF%D1%80%D0%BE%D0%B9%D1%82%D0%B8%20%D0%B2%20%D0%BC%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%20%D0%9C%D0%B5%D0%B1%D0%B5%D0%BB%D1%8C%D0%B4%D0%BE%D1%80%D1%84" data-service="twitter"><span class="b-share-icon b-share-icon_twitter"></span></a></span></div></div>
</div>
<div class="block-tx"><div class="page-news_cont"><h2>Добро пожаловать в раздел "О НАС"</h2>
<p>Компания Мебельдорф - предоставляет мебель от ведущих украинских и зарубежных производителей уже более 10 лет.&nbsp;</p>
<p>Мы работаем без посредников, при этом вы не переплачиваете.&nbsp;Вы можете <strong><span style="text-decoration: underline;">написать нам</span></strong> в разделе контактной информации и мы свяжемся с вами.</p>
<p>У нас вы покупаете качественную мебель с гарантией, варианты которой вы можете посмотреть в нашем <span style="text-decoration: underline;"><strong><a href="katalog.html" target="_blank" rel="noopener">интернет-каталоге мебели</a></strong></span> или витрине магазина Мебельдорф.</p>
<p>У нас вы получите мебель со всеми услугами в Днепре:</p>
<ul>
<li>доставка;</li>
<li>занос;</li>
<li>сборка;</li>
<li>установка.</li>
</ul>
<p>А также мы осуществляем отправку в любой город Украины.</p>
<h2>Работа с покупателями в магазине Мебельдорф:</h2>
<p><img class="" src="assets/images/o_nas/6.jpg" alt="Работа продовца в магазине Мебельдорф" width="800" height="534"></p>
<p><img class="" src="assets/images/o_nas/5.jpg" alt="Работа продовца в магазине Мебельдорф 2" width="800" height="534"></p>
<p><img class="" src="assets/images/o_nas/4.jpg" alt="Работа продовца в магазине Мебельдорф 3" width="800" height="534"></p>
<p><img class="" src="assets/images/o_nas/3.jpg" alt="Работа продовца в магазине Мебельдорф 4" width="800" height="534"></p>
<p><img class="" src="assets/images/o_nas/2.jpg" alt="Работа продовца в магазине Мебельдорф 6" width="800" height="534"></p>
<p><img class="" src="assets/images/o_nas/1.jpg" alt="Работа продовца в магазине Мебельдорф 7" width="799" height="534"></p>
<h2>Как пройти в наш магазин Мебельдорф:</h2>
<p><iframe src="https://www.youtube.com/embed/QAQTOJ9XhtE" width="95%" height="350" frameborder="0" allowfullscreen="allowfullscreen"> rel="nofollow"</iframe></p>
<h2>Магазин Мебельдорф на карте:</h2>
<p><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d819.8461601471824!2d35.02091713926282!3d48.472340997301366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x706ab5575513b98b!2zItCc0LXQsdC10LvRjNC00L7RgNGEIg!5e1!3m2!1sru!2sua!4v1535175198702" width="95%" height="350" frameborder="0" allowfullscreen="allowfullscreen">  rel="nofollow" </iframe></p></div></div>
</div>
<div class="clearfix"></div>
</section>